### ISSUE TITLE
React should be a peerDependency

### ISSUE THREAD

**Issue by lfittl** [uhoh-itsmaciek/react-pg-explain#2]
Getting this error unless the react version matches exactly:

```
Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:193493:19)
    at resolveDispatcher (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:194878:32)
    at useState (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:194902:24)
    at Node (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:193096:73)
    at renderWithHooks (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:183597:22)
    at mountIndeterminateComponent (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:185754:17)
    at beginWork (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:186389:20)
    at performUnitOfWork (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:190433:16)
    at workLoop (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:190474:28)
    at renderRoot (http://localhost:5000/packs/js/1-92a6ab1dd93f915cb75b.chunk.js:190554:11)
```

That seems to be due to `react` being a dependency rather than a peerDependency, per https://reactjs.org/warnings/invalid-hook-call-warning.html

"Maybe a library you’re using incorrectly specifies react as a dependency (rather than a peer dependency)."

**Comment by msakrejda** [comment]
Yeah, think this is the "two copies of React" scenario, so the hooks from this library don't play nice with application hooks. As you said, I think #1 fixes this.
